// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc1735.Team17352013.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import org.usfirst.frc1735.Team17352013.Robot;

/**
 *
 */
public class AutonomousMain extends CommandGroup {
    
    public  AutonomousMain() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        
        /*
                public boolean getAutoMode(String mode) {
        if() {
            return true;
        } else {
            return false;
        }
    }
        */
        addParallel(new DriveAuto());
        addParallel(new ShooterOn());
        addSequential(new Delay(1.0));
        addSequential(new ShootSequence());
        addSequential(new Delay(1.5));
        addSequential(new BeltFowardAuto());
        addSequential(new ShootSequence());
        addSequential(new Delay(1.5));
        addSequential(new BeltFowardAuto());
        addSequential(new ShootSequence());
        addSequential(new ShooterOff());
        
    }
}
